import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          OnboardPage(),
        ]),
      ),
    );
  }
}

class OnboardPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.19, 0.98),
              end: Alignment(-0.19, -0.98),
              colors: [Color(0xFF194932), Color(0xFF006333)],
            ),
            shape: RoundedRectangleBorder(
              side: BorderSide(width: 15),
              borderRadius: BorderRadius.circular(30),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 58,
                top: 118,
                child: SizedBox(
                  width: 326,
                  height: 100,
                  child: Text(
                    'Save The Wood,\nSave The World',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 33,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 111.52,
                top: 277,
                child: Transform(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(0.32),
                  child: Container(
                    width: 109.38,
                    height: 152.43,
                    child: Stack(
                      children: [
                        Positioned(
                          left: -6.62,
                          top: 19.71,
                          child: Transform(
                            transform: Matrix4.identity()
                              ..translate(0.0, 0.0)
                              ..rotateZ(0.32),
                            child: Container(
                              width: 109.38,
                              height: 131.65,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: -30.43,
                                    top: 90.65,
                                    child: Transform(
                                      transform: Matrix4.identity()
                                        ..translate(0.0, 0.0)
                                        ..rotateZ(0.32),
                                      child: Container(
                                        width: 109.38,
                                        height: 36.03,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFF933F17),
                                          shape: OvalBorder(
                                            side: BorderSide(
                                                width: 2,
                                                color: Color(0xFF5C1D0C)),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Transform(
                                      transform: Matrix4.identity()
                                        ..translate(0.0, 0.0)
                                        ..rotateZ(0.32),
                                      child: Container(
                                        width: 109.38,
                                        height: 113.63,
                                        decoration: BoxDecoration(
                                          color: Color(0xFF933F17),
                                          border: Border.only(
                                            left: BorderSide(
                                                width: 2,
                                                color: Color(0xFF5C1D0C)),
                                            top: BorderSide(
                                                width: 1,
                                                color: Color(0xFF5C1D0C)),
                                            right: BorderSide(
                                                width: 2,
                                                color: Color(0xFF5C1D0C)),
                                            bottom: BorderSide(
                                                color: Color(0xFF5C1D0C)),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 17.68,
                                    top: 54.99,
                                    child: Transform(
                                      transform: Matrix4.identity()
                                        ..translate(0.0, 0.0)
                                        ..rotateZ(0.32),
                                      child: Container(
                                        width: 39.05,
                                        height: 37.84,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 2.44,
                                              top: 5.16,
                                              child: Transform(
                                                transform: Matrix4.identity()
                                                  ..translate(0.0, 0.0)
                                                  ..rotateZ(0.32),
                                                child: Container(
                                                  width: 30.31,
                                                  height: 28.84,
                                                  decoration: BoxDecoration(
                                                      color: Color(0xFFFFA753)),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 0,
                          child: Transform(
                            transform: Matrix4.identity()
                              ..translate(0.0, 0.0)
                              ..rotateZ(0.32),
                            child: Container(
                              width: 109.38,
                              height: 42.96,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Transform(
                                      transform: Matrix4.identity()
                                        ..translate(0.0, 0.0)
                                        ..rotateZ(0.32),
                                      child: Container(
                                        width: 109.38,
                                        height: 42.96,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFFFFA54F),
                                          shape: OvalBorder(
                                            side: BorderSide(
                                                width: 2,
                                                color: Color(0xFF5C1D0C)),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 194,
                top: 443.30,
                child: Transform(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(-0.43),
                  child: Container(
                    width: 109.38,
                    height: 152.43,
                    child: Stack(
                      children: [
                        Positioned(
                          left: 8.61,
                          top: 18.92,
                          child: Transform(
                            transform: Matrix4.identity()
                              ..translate(0.0, 0.0)
                              ..rotateZ(-0.43),
                            child: Container(
                              width: 109.38,
                              height: 131.65,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 39.60,
                                    top: 87.03,
                                    child: Transform(
                                      transform: Matrix4.identity()
                                        ..translate(0.0, 0.0)
                                        ..rotateZ(-0.43),
                                      child: Container(
                                        width: 109.38,
                                        height: 36.03,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFF933F17),
                                          shape: OvalBorder(
                                            side: BorderSide(
                                                width: 2,
                                                color: Color(0xFF5C1D0C)),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Transform(
                                      transform: Matrix4.identity()
                                        ..translate(0.0, 0.0)
                                        ..rotateZ(-0.43),
                                      child: Container(
                                        width: 109.38,
                                        height: 113.63,
                                        decoration: BoxDecoration(
                                          color: Color(0xFF933F17),
                                          border: Border(
                                            left: BorderSide(
                                                width: 2,
                                                color: Color(0xFF5C1D0C)),
                                            top: BorderSide(
                                                width: 1,
                                                color: Color(0xFF5C1D0C)),
                                            right: BorderSide(
                                                width: 2,
                                                color: Color(0xFF5C1D0C)),
                                            bottom: BorderSide(
                                                color: Color(0xFF5C1D0C)),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 50.45,
                                    top: 28.14,
                                    child: Transform(
                                      transform: Matrix4.identity()
                                        ..translate(0.0, 0.0)
                                        ..rotateZ(-0.43),
                                      child: Container(
                                        width: 39.05,
                                        height: 37.84,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 5.30,
                                              top: 2.11,
                                              child: Transform(
                                                transform: Matrix4.identity()
                                                  ..translate(0.0, 0.0)
                                                  ..rotateZ(-0.43),
                                                child: Container(
                                                  width: 30.31,
                                                  height: 28.84,
                                                  decoration: BoxDecoration(
                                                      color: Color(0xFFFFA753)),
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                        Positioned(
                          left: 0,
                          top: 0,
                          child: Transform(
                            transform: Matrix4.identity()
                              ..translate(0.0, 0.0)
                              ..rotateZ(-0.43),
                            child: Container(
                              width: 109.38,
                              height: 42.96,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Transform(
                                      transform: Matrix4.identity()
                                        ..translate(0.0, 0.0)
                                        ..rotateZ(-0.43),
                                      child: Container(
                                        width: 109.38,
                                        height: 42.96,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFFFFA54F),
                                          shape: OvalBorder(
                                            side: BorderSide(
                                                width: 2,
                                                color: Color(0xFF5C1D0C)),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 659,
                child: Container(
                  width: 313,
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Sign In',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 22,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w600,
                          height: 0,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 750,
                child: Container(
                  width: 313,
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: Color(0xFFFFA54F),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'Sign Up',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 22,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w600,
                          height: 0,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
